# Generated by Django 5.0.4 on 2024-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_completed",
            field=models.BooleanField(choices=[(0, "Не завершено"), (1, "Завершено")]),
        ),
        migrations.AlterField(
            model_name="seriesbook",
            name="is_completed",
            field=models.BooleanField(choices=[(0, "Не завершено"), (1, "Завершено")]),
        ),
    ]
