# Generated by Django 5.0.4 on 2024-04-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libapp", "0003_author_user_book_user_seriesbook_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seriesbook",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="libapp.author",
            ),
        ),
    ]
