# Generated by Django 5.0.4 on 2024-04-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libapp", "0004_alter_seriesbook_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="libapp.seriesbook",
            ),
        ),
    ]
