# Generated by Django 5.0.4 on 2024-04-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libapp", "0005_alter_book_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seriesbook",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="seriesbook",
            name="rating",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
